### ISSUE TITLE
Planned information - feedback welcome

### ISSUE THREAD

**Issue by solidpixel** [ARM-software/libGPUInfo#1]
This library is still in development, but we wanted to kick off a discussion about what information we can expose. The current plan includes the following:

## GPU properties

* Renderer (Model and core count, string)
* Model number (enum)
* Core count (uint)
* L2 cache count (uint)
* L2 cache size (uint)
* Bus interface bits (uint)

## Core properties

* fp32 FMAs per clock (uint)
* Bilinear samples per clock (uint)
* Pixels per clock (uint)

**Comment by darksylinc** [comment]
Hi!

First, thanks for listening for feedback and acting upon it!

Second; as you know what we are mostly interested is knowing the relative performance of each model.

I've been thinking of how to approach this problem based on the clues you provided from [HWCPipe](https://github.com/ARM-software/HWCPipe).

What I had in mind is:

1. Run our own benchmark on e.g. G78 MP14, assign it some score and record: score, num cores, core freq.
2. Calculate it like this:
```cpp

uint recorded_score = 15000; // obtained empirically for this device_id
uint recorded_system_num_cores = ...; // recorded, on database; from the device that calculated recorded_score
uint recorded_system_core_freq = ...; // recorded, on database

uint system_num_cores = ...; // fetched at runtime, on running system
uint system_core_freq = ...;; // fetched at runtime, on running system

uint final_score = (recorded_score * system_num_cores * system_core_freq) / (recorded_system_num_cores * recorded_system_core_freq);
```

I was thinking that doing this per `device_id` to get a rough estimation of the device relative performance to what is known on database.

Do you think this is a reasonable approach?

I've read that some Mali GPUs may have hybrid cores. Do you see how it'd need to be corrected to get a better estimate?

Ideally we'd build a database with score, device_id + core_count + core_freq (i.e. steam hw survey style); but that's only a valid approach after we go live and popular.

**Comment by solidpixel** [comment]
> Run our own benchmark on e.g. G78 MP14, assign it some score and record: score, num cores, core freq.

Running benchmarks that look like your real workload is always going to give you the best numbers. GPUs are complex, and spec sheet numbers only get you so far (but certainly better than nothing). 

There are two usual challenges that we run in to. 

Firstly, finding out operating frequency is harder than it looks. The driver doesn't even know (which is why I can't provide it here), because power/frequency control is provided by the SoC manufacturer.  Having a known workload that maxes out the GPU, and using HWCPipe to measure GPU cycles is normally a good approximation. 

Secondly, finding out the thermally stable operating frequency normally means running benchmarks for 5-15 minutes. Certainly the kind of thing you can do in a lab, but not the kind of thing you can do on a user's device at install time. How much of this is an issue really depends how hard your content depends to push the devices.

> I've read that some Mali GPUs may have hybrid cores. Do you see how it'd need to be corrected to get a better estimate?

There are two GPU models that can mix core sizes inside the GPU, which is where the "MP/MC" naming comes from, but it's only for some configurations.   

* Mali-G31 "MP3" is a 3 pixel per clock GPU, but "MC2" two cores  (one big and one small).
* Mali-G51 "MP3" is as above, with the G51 shader core.
* Mali-G51 "MP5" is a 5 pixel per clock GPU, with "MC3" three cores (two big and one small).

In reality you very rarely see these in smartphones, so personally I wouldn't worry about them, they are mostly used in consumer devices such as HDTV. For smartphones nearly all designs use the MP2/MP4 designs which only consist of big cores. 

The one that you will find more of is the Mali-G52 entry-level GPU, which comes in two flavors. The shader cores are both 2 pixel per clock, but the low area variant has one less arithmetic pipeline (2 rather than 3). This will be reflected in the FMA stats, if I can find a way of digging it out of the kernel query on those devices (not 100% sure I can yet). If I can't I'll statically report the size of the smaller config, as this is the only save option for developers - you can't work with 33% of your FMA performance vanishing. 

> Update: Please clarify what "pixels per clock" mean? That sounds... vague. Last time I recall GPU vendors talking about pixels per clock was during Fixed Function era.

Shader core peak pixels per clock for tile write (which is also the same as the peak fragment retire for blending into tile memory). 

I don't know how useful it is for 99% of content, but I like to include it because when we talk about shader core count, you often need to know about the size of the shader core you are working with. Mali cores have been getting bigger, and we generally size the generations by talking about "pixels per clock" of the core chassis. Mali-200 up was a "1 pixel per clock chassis", Mali-G76 moved to a "2 pixel per clock chassis", and the latest GPUs move up to a "4 pixel per clock chassis".

Faster cores, but obviously bigger, so core counts are expected to drop in proportion for a given performance point.

**Comment by darksylinc** [comment]
> Secondly, finding out the thermally stable operating frequency normally means running benchmarks for 5-15 minutes. Certainly the kind of thing you can do in a lab, but not the kind of thing you can do on a user's device at install time. How much of this is an issue really depends how hard your content depends to push the devices.

OK, perhaps I should clarify what I understand by "rough estimation".

Of course finding a fine-tuned performance in mobile is hard because of all the issues you mention (very heterogeneous HW offerings in the market, vendor specific OS scheduler customization including per-game profiles specifically set by manufacturers, very different thermal cooling effciency out there etc) that rarely appear on PC.
Even how warm the hand of the player is or how they hold the phone has an impact.

However we offer several graphical options (which boil down to resolution, shadows quality, reflections) and for instance Redmi 4X Adreno 505 (the slowest phone we support) performs as follow:

- Everything on low or disabled: 33ms per frame
- Resolution on medium, rest disabled: 50ms
- Everything on maximum and enabled: 250ms

That is for the same phone for the first 5 minutes, we have around 7.5x performance gap between minimum and max settings (TBH the minimum settings have been dictated by this phone).

What we just want is that when the user opens the game for the first time it runs at 60 fps (or the maximum the phone can do at minimum settings). If he later wishes to change the default, or experience diminishes because it's thermal throttling and user needs to tweak it; then so be it.

Maybe we got it wrong, and some phone runs at 30-40 fps by default when it could run at 60. That's acceptable. We want to avoid it, but it's acceptable.

But what we **really** don't want is the game running at 10fps when it could be running at 30 or 60 because the default settings are wrong.

We also don't want to set the settings very low when the game could easily handle everything on Medium or High at 60 fps. This is because our game looks pretty and unfortunately Android games have a bad reputation of blatantly lying about their graphics (or even gameplay) on promotional materials in Ads & on the Store. We don't want them to think we are deceiving them. The pictures we present on the Store are screenshots taken in-game.

For this end, public benchmarks have been enough for Adreno: the score translates very well. If my Adreno 630 runs at 80 fps with certain settings and had a public score on a popular site of 15000; and that same benchmark shows a score of 7500 for Adreno 620 (note: I'm making up the numbers, not real numbers); then I can be quite confident that most Adreno 620 phones will run our game at roughly 40 fps with those same settings.

We found out with Mali that this is not remotely the case. Public benchmarks don't translate in any way to predict relative performance of other Mali GPUs from the same generation, or even the same device_id!

That's why I'm thinking of the formula: so we can have a rough estimate of relative performance in order to set _sane_ defaults.

We are not expecting to get "OMG PERFECT DEFAULTS! Runs solid 60 fps after 1hs of gameplay!!". That's not how mobile works and we are aware of it.

> Shader core peak pixels per clock for tile write. For Mali, this is also the same as the peak fragment retire for blending into tile memory.

Ahh! Thanks. Yes, this is somewhat similar to ROP performance; since TBDRs don't have ROPs.

So I think the best way to measure how relevant the pixels per clock is, is via MSAA: If certain Mali GPU diminishes performance goes when going from MSAA 2x to 4x; then pixel clock plays an important role.

If performance remains the same when going from no MSAA to 4xMSAA, then I can pretty much ignore this info unless it affects core count too much.
